language: php
php:
  - "5.4"
  - "5.5"
  - "5.6"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y phantomjs screen
before_script:
  - "sudo export DISPLAY=:99.0"
  - "sudo sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - sudo rackup  # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
  - mysql -e 'create database vagrant;'
  - mysql -e "GRANT ALL PRIVILEGES ON vagrant.* TO 'vagrant'@'%' IDENTIFIED BY 'vagrant'" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON vagrant.* TO 'vagrant'@'localhost' IDENTIFIED BY 'vagrant'" -uroot
  - mysql -u root --password="" vagrant < simplelance.sql
  - screen -S server -d -m phantomjs --webdriver=4444
  - "composer self-update"
  - "composer install --dev --no-interaction"
script:
  - ./vendor/bin/codecept run
