sudo: false
language: php
addons:
  hosts:
    - simplelance.dev
php:
  - "5.5"
  - "5.6"
  - "hhvm"
  - "nightly"
before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead;'
  - mysql -e "GRANT ALL PRIVILEGES ON homestead.* TO 'homestead'@'%' IDENTIFIED BY 'secret'" -uroot
  - "composer self-update"
  - "composer install --no-interaction"
  - php artisan migrate --force
  - php artisan db:seed --force
script:
  - ./vendor/bin/phpunit
